### ISSUE TITLE
kogs: kogsgameconfiglist spam 

### ISSUE THREAD

**Issue by Alrighttt** [dimxy/komodo#23]
The `kogsgameconfiglist` rpc output can be spammed by keys other than the system key. 

https://github.com/dimxy/komodo/blob/3fbbc3c1b0a0e76785f2d11202979936a7a528e6/src/cc/kogs.cpp#L671

I see there is a check here that attempts to prevent this; however this is simply checking whether the pubkey in the transaction's OP_RETURN output has the system key in it. This data in the OP_RETURN can be changed arbitrarily and allows any node to add entries to `kogsgameconfiglist`'s output.

**Comment by Alrighttt** [comment]
This same issue applies to `kogscreatekogs` / `kogskoglist` as well. 

If this is used with `kogskoglist`, it's possible to create kogs from keys other than the system key. Still unsure if these NFTs are usable or not, but `kogsobjectinfo` will show them as created by the system key. 

This NFT was created without having access to the `originatorPubKey` key.
```
komodo-cli -ac_name=MYKOG kogsobjectinfo 3db271aea411c072991c8393af912404931c9ffaede136130d4342a48a9f8433
{
  "result": "success",
  "evalcode": "f4",
  "objectType": "K",
  "objectDesc": "KOGSID_KOG",
  "version": "2",
  "nameId": "kog2",
  "descriptionId": "nft",
  "originatorPubKey": "03963e175c3f61844109a2ceb450bdb166c914bf73e2a71a2be3f6d27ac9b3f400",
  "creationtxid": "3db271aea411c072991c8393af912404931c9ffaede136130d4342a48a9f8433",
  "imageId": "image-02",
  "setId": "myset",
  "subsetId": "mysubset",
  "printId": "0",
  "appearanceId": "2175"
}
```

**Comment by dimxy** [comment]
when a kog or gameconfig is used LoadGameObject checks if it is created with the syspk, so such objects should be ignored but currently we can't prevent creation of them
(when we switch to cc v2 we will be able to prevent such creation of objects with not the syspk)

**Comment by Alrighttt** [comment]
These "counterfeit" gameconfigs can be used to play games. `such objects should be ignored` is not the case for gameconfigs at least.

**Comment by dimxy** [comment]
archived due to the closed project
