### ISSUE TITLE
kogs: adding creationtxid to baton ensclosure object can cause tokens to become unrecoverable 

### ISSUE THREAD

**Issue by Alrighttt** [dimxy/komodo#28]
As the title says, adding `creationtxid` to a baton's enclosure object can cause a games containers and slammer tokens to be unrecoverable. It seems these games are not able to be autofinished by the syspk or by the players of the game. 

This can be reproduced by adding this line to kogs.cpp, creating a game from this node and attempting to play the game(`kogsstartgame`, `kogscommitrandoms`, `kogsrevealrandoms`, `kogscreatefirstbaton`) until it fails at `kogsslamdata`.

`enc.creationtxid = Parseuint256("deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef");`
https://github.com/dimxy/komodo/blob/4272e906a787c885013348c5cf281d5561b3b534/src/cc/kogs.cpp#L941

This same method of adding creationtxid to enclosures that should not have it can be used to add invalid game ids to a player's game list by creating a `kogsstartgame` transaction with creationtxid. This is likely to break GUIs if they assume all txids in `kogsgamelist` response are valid game objects. 

I suspect there are more instances of this causing issues. A good solution to this may be to implement CCv2, so that each opreturn can be fully validated.

**Comment by Alrighttt** [comment]
An example of this can be found on the `MYKOG` chain with the gameid `bc11b4589f56084c2b0e7d25d8adf0b0cf31fc794cd83ff6b342ea831f87f84d`

**Comment by dimxy** [comment]
archived due to the closed project
