### ISSUE TITLE
kogs: Broken authetication for kogsadvertiseplayer and duplicate entries in kogsadvertisedplayerlist

### ISSUE THREAD

**Issue by Alrighttt** [dimxy/komodo#29]
It seems that the function `FindAdvertisings` is meant to filter out any advertising batons that were not created by the playerid's originatorPubKey. However, this doesn't seem to work as intended and anyone can create a seemingly valid advertising transaction for any playerid. I understand that only PLAY_FOR_FUN is implemented at the moment, but I believe this will lead to issues once the other ops are implemented. 

This line in particular seems to try to filter out advertising transactions that do not include an input from the originatorPubKey, but I believe this may be checking against the playerid creation transaction rather than the advertising transaction. 
https://github.com/dimxy/komodo/blob/4272e906a787c885013348c5cf281d5561b3b534/src/cc/kogs.cpp#L1269

This can be reproduced by commenting this if statement and using the `kogsadvertiseplayer` rpc with a playerid of another player. 
https://github.com/dimxy/komodo/blob/4272e906a787c885013348c5cf281d5561b3b534/src/cc/kogs.cpp#L2985

A similar method can be used to create duplicate entries in the kogsadvertisedplayerlist. Simply comment this if statement and use the `kogsadvertiseplayer` rpc with a playerid already in the list. 
https://github.com/dimxy/komodo/blob/4272e906a787c885013348c5cf281d5561b3b534/src/cc/kogs.cpp#L2994

I've not tested the effects of the duplicate entries on game logic. Although it does seem that it will use the first advertise transaction it finds from the marker address. 

This issue can likely be solved with CCv2 and adding validation of kogsadvertiseplayer OP_RETURNs.

**Comment by dimxy** [comment]
there is commented code in LoadGameObject() that checks that encOrigPk signed the tx (should be uncommented)

**Comment by dimxy** [comment]
archived due to the closed project
