### ISSUE TITLE
kogs:  No authentication on adding kogs to containers

### ISSUE THREAD

**Issue by Alrighttt** [dimxy/komodo#31]
I'm not sure this is a practical issue, but it's possible to add kogs to containers that do not belong to you. 

This can be reproduced by using `kogsaddkogdstocontainer` with a kog you own and a container you do not own.

**Comment by Alrighttt** [comment]
This is a practical issue. I am able to add normal tokens to a container that does not belong to me. If this container is used in a game, the game will fail and will be unrecoverable. 

the game will fail to decode batons in this case:
```
{
  "result": "success",
  "evalcode": "f4",
  "objectType": "G",
  "objectDesc": "KOGSID_GAME",
  "version": "1",
  "nameId": "",
  "descriptionId": "",
  "originatorPubKey": "031fed192588f1ce03ec398705576083fac76f6e8f37bc0546e3f79fdbe43fc4d7",
  "creationtxid": "9ba54cec796a5588b012a30970668a701f5769a1d33933a629ffeee89ca840d2",
  "gameinfo": {
    "error": "can't load baton"
  }
}
```

**Comment by dimxy** [comment]
"error": "can't load baton" might be related to another issue,
but i think it is better to check that only 'my' kogs could be added to a container

**Comment by dimxy** [comment]
archived due to closed project
