### ISSUE TITLE
kogs: games disappear from kogsgamelist(my) after kogscommitrandoms

### ISSUE THREAD

**Issue by Alrighttt** [dimxy/komodo#33]
Game ids will disappear from the `kogsgamelist my` result after one player does `kogscommitrandoms`. 

It would be useful if `kogsgamelist` could be split up into three categories: not started, in progress and finished.

**Comment by dimxy** [comment]
basically it disappears from 'kogsgamelist my' after kogsrevealrandoms as this rpc spends playerpk vout.
I need to add an additional playerpk vout that will never be spent just for 'kogsgamelist my'

**Comment by dimxy** [comment]
added a vout to players pk to get 'kogsgamelist my'

**Comment by dimxy** [comment]
archived due to closed project
