### ISSUE TITLE
tokenv2create daemon crash

### ISSUE THREAD

**Issue by NutellaLicka** [dimxy/komodo#49]
### Describe the issue
The daemon crashes when trying to create an NFT without any NFT data in the RPC code

### Can you reliably reproduce the issue?
Yes, just try and create an NFT without any data

### Expected behaviour
An error code should populate saying data is a required field. Maybe even mention the arbitrary data evalcode 00

### The version of Komodo you were using:
`test-eval-nft` branch

### Any extra information that might be useful in the debugging process.
```./komodo-cli -ac_name=TKLTEST tokenv2create NONFTDATA1 0.00000001 "This NFT is created to test when no NFT data is added"```
```error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)```

It throws this error code and crashes the daemon.

**Comment by dimxy** [comment]
fixed in the tokel branch (the error was in code in development, in a test branch)
